version: 0.0
os: linux
files:
  - source: /
    destination: /home/nodeapp/node-express-typescript
hooks:
  BeforeInstall:
    - location: stop_server.sh
      timeout: 300
  AfterInstall: 
    - location: start_server.sh
      timeout: 300